#!/usr/bin/env python3
"""Generate test data readiness report (ISO/IEC/IEEE 29119-3 §8.5, §8.7)."""

from __future__ import annotations

import argparse
from dataclasses import dataclass
from datetime import datetime, timezone
from pathlib import Path
from typing import List

from rtm_utils import ROOT

REPORTS_DIR = ROOT / "reports"


@dataclass
class DataRequirement:
    ident: str
    purpose: str
    location: Path
    owner: str
    retention: str
    reset: str
    rtm_ids: List[str]

    def status(self) -> str:
        return "Present" if self.location.exists() else "Missing"

    def rel_location(self) -> Path:
        try:
            return self.location.relative_to(ROOT)
        except Exception:
            return self.location


DATA_REQUIREMENTS: List[DataRequirement] = [
    DataRequirement(
        ident="DATA-UNDO",
        purpose="Action sequences for undo/redo stack tests",
        location=ROOT / "Test" / "Unit Tests" / "Undo Redo Core",
        owner="Automation QA",
        retention="Ephemeral per run; regenerated by unit tests",
        reset="Reset by rerunning suite; logs archived in PR artifacts",
        rtm_ids=["UT-001", "NF-001"],
    ),
    DataRequirement(
        ident="DATA-EDITORPOS",
        purpose="INI/coordinate fixtures for editor position tests",
        location=ROOT / "Test" / "Unit Tests" / "Editor Position",
        owner="Automation QA",
        retention="Ephemeral per run; regenerated by unit tests",
        reset="Reset by rerunning suite; logs/INI samples archived in PR artifacts",
        rtm_ids=["UT-002", "NF-002"],
    ),
    DataRequirement(
        ident="DATA-TEXTICON",
        purpose="Text separator samples for tokenization tests",
        location=ROOT / "Test" / "Unit Tests" / "Text-Based VI Icon Tests",
        owner="Automation QA",
        retention="Ephemeral per run; regenerated by unit tests",
        reset="Reset by rerunning suite; logs archived in PR artifacts",
        rtm_ids=["TB-001", "NF-003"],
    ),
    DataRequirement(
        ident="DATA-TRW",
        purpose="TRW checklist artifact for workflow verification",
        location=ROOT / "docs" / "requirements" / "TRW_Verification_Checklist.md",
        owner="Automation QA",
        retention="Persistent in repo; updated via PRs",
        reset="Versioned in Git; snapshots archived in PR artifacts",
        rtm_ids=["TRW-001"],
    ),
]


def timestamp_utc() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%SZ")


def build_report(run_id: str) -> Path:
    REPORTS_DIR.mkdir(parents=True, exist_ok=True)
    path = REPORTS_DIR / f"test-data-readiness-{run_id}.md"

    missing = [req for req in DATA_REQUIREMENTS if req.status() != "Present"]

    lines: List[str] = []
    lines.append("# Test Data Readiness Report (ISO/IEC/IEEE 29119-3 §8.5, §8.7)")
    lines.append("")
    lines.append(f"- Generated: {timestamp_utc()}")
    lines.append(f"- Run ID: `{run_id}`")
    lines.append(f"- Source: `docs/testing/test-data-requirements.md`")
    lines.append("")
    lines.append("## Summary")
    lines.append(f"- Data requirements: {len(DATA_REQUIREMENTS)}")
    lines.append(f"- Present: {len(DATA_REQUIREMENTS) - len(missing)}")
    lines.append(f"- Missing: {len(missing)}")
    if missing:
        lines.append("- Missing items:")
        for req in missing:
            lines.append(f"  - {req.ident} at `{req.rel_location()}`")
    else:
        lines.append("- Missing items: none")
    lines.append("")
    lines.append("## Data Requirements Status")
    lines.append("| ID | Purpose | Location | Owner | Retention | Reset/Archiving | RTM IDs | Status |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- | --- |")
    for req in DATA_REQUIREMENTS:
        lines.append(
            "| {id} | {purpose} | `{loc}` | {owner} | {retention} | {reset} | {rtm} | {status} |".format(
                id=req.ident,
                purpose=req.purpose,
                loc=req.rel_location(),
                owner=req.owner,
                retention=req.retention,
                reset=req.reset,
                rtm=", ".join(req.rtm_ids),
                status=req.status(),
            )
        )

    path.write_text("\n".join(lines), encoding="utf-8")
    return path, missing


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate test data readiness report.")
    parser.add_argument(
        "--run-id",
        default="local",
        help="Run identifier (default: local or use $GITHUB_RUN_ID).",
    )
    args = parser.parse_args()
    run_id = args.run_id or "local"

    report_path, missing = build_report(run_id)
    rel = report_path.relative_to(ROOT)
    print(f"Wrote {rel}")
    if missing:
        print("Missing data requirements:")
        for req in missing:
            print(f"- {req.ident} at {req.rel_location()}")
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
