blank_issues_enabled: false

contact_links:
  - name: ❓ Join Our Discord Server
    url:  https://discord.gg/q4d3ggrFVA
    about: "Let us help you if you hit a roadblock!"

  - name: 📖 Read the Docs
    url: https://ni.github.io/labview-icon-editor/
    about: "Check the documentation for common questions before opening an issue."

issue_templates:
  - name: 🐞 Bug Report
    path: bug_report.yml
    description: "Report a reproducible issue."
    labels: ["Issue group: Bug"]
    
  - name: 🚀 Feature Request
    path: feature_request.yml
    description: "Suggest a new feature or enhancement."
    labels: ["Type: Enhancement"]
