name: "Add LabVIEW INI Token"
description: "Runs AddTokenToLabVIEW.ps1 to add a Localhost.LibraryPaths token to the LabVIEW INI file."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Run AddTokenToLabVIEW.ps1
      shell: pwsh
      run: |
        & "${{ github.action_path }}/AddTokenToLabVIEW.ps1" \
          -MinimumSupportedLVVersion ${{ inputs.minimum_supported_lv_version }} \
          -SupportedBitness ${{ inputs.supported_bitness }} \
          -RepoRoot "${{ inputs.repo_root }}"
inputs:
  minimum_supported_lv_version:
    description: 'LabVIEW 2021 (21.0)'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
  repo_root:
    description: 'Workspace root path'
    required: true
