services:
  vipm-labview:
    build: .
    image: vipm-labview
    stdin_open: true
    tty: true
    env_file:
      - .env
    volumes:
      - ../../..:/workspace
    working_dir: /workspace
    command: bash
