<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AssemblyName>XCli</AssemblyName>
    <OutputType>Exe</OutputType>
    <PublishSingleFile>true</PublishSingleFile>
    <SelfContained>true</SelfContained>
    <PublishTrimmed>false</PublishTrimmed>
    <RootNamespace>XCli</RootNamespace>
    <PackageReadmeFile>README.nupkg.md</PackageReadmeFile>
    <RuntimeIdentifiers>win-x64;linux-x64;osx-x64;osx-arm64</RuntimeIdentifiers>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Telemetry\Telemetry.csproj" />
    <ProjectReference Include="..\SrsApi\SrsApi.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="CsvHelper" Version="30.0.1" />
    <PackageReference Include="JsonSchema.Net" Version="6.0.0" />
    <PackageReference Include="Microsoft.NET.ILLink.Tasks" Version="8.0.22" PrivateAssets="all" />
    <PackageReference Include="YamlDotNet" Version="15.1.2" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\README.nupkg.md" Pack="true" PackagePath="" Condition="Exists('..\README.nupkg.md')" />
    <None Include="..\..\README.nupkg.md" Pack="true" PackagePath="" Condition="Exists('..\..\README.nupkg.md')" />
  </ItemGroup>
</Project>
