services:
  seed:
    build:
      context: ../../seed
      dockerfile: Dockerfile
    image: seed-local:latest
    stdin_open: true
    tty: true
    volumes:
      - ../../..:/workspace
    working_dir: /workspace
    command: ["seed", "--help"]
