name: "Close LabVIEW"
description: "Runs Close_LabVIEW.ps1 to gracefully shut down a LabVIEW instance."
runs:
  using: "composite"
  steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        clean: false

    - name: Run Close_LabVIEW.ps1
      shell: pwsh
      run: |
        & "${{ github.action_path }}/Close_LabVIEW.ps1" `
          -MinimumSupportedLVVersion ${{ inputs.minimum_supported_lv_version }} `
          -SupportedBitness ${{ inputs.supported_bitness }} `
          -TimeoutSeconds ${{ inputs.timeout_seconds }}
inputs:
  minimum_supported_lv_version:
    description: 'LabVIEW 2021 (21.0)'
    required: true
  supported_bitness:
    description: '32 or 64'
    required: true
  timeout_seconds:
    description: 'How long to wait for LabVIEW to exit before failing'
    required: false
    default: 120
