#Requires -Version 7.0
[CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='Low')]
param(
  [Parameter()][ValidateSet('2021','2023','2025')][string]$LabVIEWVersion = '2023',
  [Parameter()][ValidateSet(32,64)][int]$Bitness = 64,
  [Parameter()][ValidateNotNullOrEmpty()][string]$Workspace = (Get-Location).Path,
  [Parameter()][int]$TimeoutSec = 600,
  [string]$FixturePath,
  [string]$ResultsRoot,
  [string]$OutputPath,
  [switch]$KeepWork,
  [switch]$SkipResourceOverlay,
  [string]$ResourceOverlayRoot
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'
$PSModuleAutoLoadingPreference = 'None'
if ([string]::IsNullOrWhiteSpace($FixturePath)) {
    throw 'FixturePath is required; supply the VIP generated by the build.'
}
if (-not (Test-Path 'variable:Global:InvokeValidateLocalStubLog')) {
    $Global:InvokeValidateLocalStubLog = @()
} elseif (-not $Global:InvokeValidateLocalStubLog) {
    $Global:InvokeValidateLocalStubLog = @()
}
$Global:InvokeValidateLocalStubLog += [pscustomobject]@{
    Command = 'Describe'
    Parameters = [pscustomobject]@{
        FixturePath        = $FixturePath
        ResultsRoot        = $ResultsRoot
        SkipResourceOverlay= $SkipResourceOverlay.IsPresent
        ResourceOverlayRoot= $ResourceOverlayRoot
    }
}
if ($OutputPath) {
    $dir = Split-Path -Parent $OutputPath
    if ($dir -and -not (Test-Path -LiteralPath $dir -PathType Container)) {
        New-Item -ItemType Directory -Path $dir -Force | Out-Null
    }
}
$summary = [pscustomobject]@{
    schema            = 'icon-editor/fixture-report@v1'
    fixtureOnlyAssets = @()
    artifacts         = @()
    manifest          = [pscustomobject]@{
        packageSmoke = [pscustomobject]@{ status = 'ok'; vipCount = 0 }
        simulation   = [pscustomobject]@{ enabled = $true }
        unitTestsRun = $false
    }
    runnerDependencies = $null
    stakeholder        = $null
    source            = [pscustomobject]@{ fixturePath = $FixturePath }
}
# Populate minimal placeholder data so downstream renderers have structured content
$fixtureArtifact = [pscustomobject]@{
    name      = if ($FixturePath) { Split-Path -Path $FixturePath -Leaf } else { 'fixture.vip' }
    path      = $FixturePath
    kind      = 'vip'
    sizeBytes = (Get-Item -LiteralPath $FixturePath -ErrorAction SilentlyContinue)?.Length ?? 0
    hash      = 'stub-hash'
}
$summary.artifacts = @($fixtureArtifact)
$summary.fixtureOnlyAssets = @(
    [pscustomobject]@{
        category  = 'resource'
        name      = 'StubResource.vi'
        hash      = 'stub-resource-hash'
        sizeBytes = 0
    }
)
$summary.runnerDependencies = [pscustomobject]@{
    fixture    = 'Tooling/deployment/runner_dependencies.vipc'
    hashMatch  = $true
}
$summary.stakeholder = [pscustomobject]@{
    generatedAt        = (Get-Date).ToString('o')
    smokeStatus        = 'ok'
    runnerDependencies = [pscustomobject]@{ matchesRepo = $true }
    customActions      = @()
    fixtureOnlyAssets  = $summary.fixtureOnlyAssets
    artifacts          = $summary.artifacts
}
if ($OutputPath) {
    $json = $summary | ConvertTo-Json -Depth 6
    Set-Content -LiteralPath $OutputPath -Value $json -Encoding utf8
}
$summary

function Test-ValidLabel {
  param([Parameter(Mandatory)][string]$Label)
  if ($Label -notmatch '^[A-Za-z0-9._-]{1,64}$') { throw "Invalid label: $Label" }
}

function Invoke-WithTimeout {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)][scriptblock]$ScriptBlock,
    [Parameter()][int]$TimeoutSec = 600
  )
  $job = Start-Job -ScriptBlock $ScriptBlock
  if (-not (Wait-Job $job -Timeout $TimeoutSec)) {
    try { Stop-Job $job -Force } catch {}
    throw "Operation timed out in $TimeoutSec s"
  }
  Receive-Job $job -ErrorAction Stop
}
