#Requires -Version 7.0
[CmdletBinding(SupportsShouldProcess=$true, ConfirmImpact='Low')]
param(
  [string]$FixturePath,
  [string]$ManifestPath,
  [string]$ResultsRoot,
  [string]$ResourceOverlayRoot,
  [switch]$SkipDocUpdate,     # retained for backward compatibility (no-op)
  [switch]$CheckOnly,         # retained for backward compatibility (no-op)
  [switch]$NoSummary,         # retained for backward compatibility (no-op)
  [Parameter()][ValidateSet('2021','2023','2025')][string]$LabVIEWVersion = '2023',
  [Parameter()][ValidateSet(32,64)][int]$Bitness = 64,
  [Parameter()][ValidateNotNullOrEmpty()][string]$Workspace = (Get-Location).Path,
  [Parameter()][int]$TimeoutSec = 600
)

Set-StrictMode -Version Latest
$ErrorActionPreference = 'Stop'

function Resolve-RepoRoot {
  param([string]$StartPath = (Get-Location).Path)
  try { (git -C $StartPath rev-parse --show-toplevel 2>$null).Trim() } catch { $StartPath }
}

if ($CheckOnly.IsPresent) {
  Write-Warning '-CheckOnly is deprecated and has no effect now that fixture reports are transient.'
}
if ($SkipDocUpdate.IsPresent) {
  Write-Verbose '-SkipDocUpdate specified; documentation updates are no longer performed by this helper.'
}

$repoRoot = Resolve-RepoRoot
$toolsRoot = Join-Path $repoRoot 'tools'
$altToolsRoot = Join-Path $repoRoot 'src/tools'
if (-not (Test-Path -LiteralPath $toolsRoot -PathType Container) -and -not (Test-Path -LiteralPath $altToolsRoot -PathType Container)) {
  throw "Unable to locate a 'tools' directory under '$toolsRoot' or '$altToolsRoot'."
}
if (-not (Test-Path -LiteralPath $toolsRoot -PathType Container) -and (Test-Path -LiteralPath $altToolsRoot -PathType Container)) {
  $toolsRoot = $altToolsRoot
}
$iconEditorToolsRoot = Join-Path $toolsRoot 'icon-editor'
if (-not (Test-Path -LiteralPath $iconEditorToolsRoot -PathType Container)) {
  $altIconRoot = Join-Path $altToolsRoot 'icon-editor'
  if (Test-Path -LiteralPath $altIconRoot -PathType Container) {
    $iconEditorToolsRoot = $altIconRoot
  } else {
    throw "Icon editor tooling not found under '$iconEditorToolsRoot' or '$altIconRoot'."
  }
}

$describeScript = Join-Path $iconEditorToolsRoot 'Describe-IconEditorFixture.ps1'
if (-not (Test-Path -LiteralPath $describeScript -PathType Leaf)) {
  throw "Descriptor script not found at '$describeScript'."
}

if (-not $FixturePath) {
  throw 'FixturePath is required; supply the VIP generated by the build.'
}
if (-not (Test-Path -LiteralPath $FixturePath -PathType Leaf)) {
  throw "Fixture VIP not found at '$FixturePath'."
}

$resultsRootResolved = if ($ResultsRoot) {
  if ([System.IO.Path]::IsPathRooted($ResultsRoot)) { $ResultsRoot } else { Join-Path $repoRoot $ResultsRoot }
} else {
  Join-Path $repoRoot 'tests/results/_agent/icon-editor'
}
if (-not (Test-Path -LiteralPath $resultsRootResolved -PathType Container)) {
  New-Item -ItemType Directory -Path $resultsRootResolved -Force | Out-Null
}

$reportPath = Join-Path $resultsRootResolved 'fixture-report.json'
$overlayResolved = $null
if ($ResourceOverlayRoot) {
  $overlayResolved = if ([System.IO.Path]::IsPathRooted($ResourceOverlayRoot)) {
    $ResourceOverlayRoot
  } else {
    Join-Path $repoRoot $ResourceOverlayRoot
  }
  if (-not (Test-Path -LiteralPath $overlayResolved -PathType Container)) {
    throw "Resource overlay path not found at '$overlayResolved'."
  }
  $overlayResolved = (Resolve-Path -LiteralPath $overlayResolved).Path
}

$describeParams = @{
  FixturePath = $FixturePath
  ResultsRoot = (Join-Path $resultsRootResolved '__describe')
  OutputPath  = $reportPath
  KeepWork    = $false
}
if ($overlayResolved) {
  $describeParams['ResourceOverlayRoot'] = $overlayResolved
} else {
  $describeParams['SkipResourceOverlay'] = $true
}

pwsh -NoLogo -NoProfile -File $describeScript @describeParams | Out-Null
$summary = Get-Content -LiteralPath $reportPath -Raw | ConvertFrom-Json -Depth 8

if ($ManifestPath) {
  $manifestEntries = @()
  foreach ($asset in ($summary.fixtureOnlyAssets | Sort-Object category, name)) {
    $rel = switch ($asset.category) {
      'script'   { Join-Path 'scripts' $asset.name }
      'test'     { Join-Path 'tests' $asset.name }
      'resource' { Join-Path 'resource' $asset.name }
      default    { Join-Path $asset.category $asset.name }
    }
    $manifestEntries += [ordered]@{
      key       = ($asset.category + ':' + $rel).ToLower()
      category  = $asset.category
      path      = $rel
      sizeBytes = ($asset.sizeBytes ?? 0)
      hash      = $asset.hash
    }
  }

  $manifestObject = [ordered]@{
    schema      = 'icon-editor/fixture-manifest@v1'
    generatedAt = (Get-Date).ToString('o')
    entries     = $manifestEntries
  }

  $manifestDir = Split-Path -Parent $ManifestPath
  if (-not (Test-Path -LiteralPath $manifestDir -PathType Container)) {
    New-Item -ItemType Directory -Path $manifestDir -Force | Out-Null
  }
  $manifestObject | ConvertTo-Json -Depth 6 | Set-Content -LiteralPath $ManifestPath -Encoding utf8
}

if ($NoSummary.IsPresent) {
  return
}

return [pscustomobject]$summary

function Test-ValidLabel {
  param([Parameter(Mandatory)][string]$Label)
  if ($Label -notmatch '^[A-Za-z0-9._-]{1,64}$') { throw "Invalid label: $Label" }
}

function Invoke-WithTimeout {
  [CmdletBinding()]
  param(
    [Parameter(Mandatory)][scriptblock]$ScriptBlock,
    [Parameter()][int]$TimeoutSec = 600
  )
  $job = Start-Job -ScriptBlock $ScriptBlock
  if (-not (Wait-Job $job -Timeout $TimeoutSec)) {
    try { Stop-Job $job -Force } catch {}
    throw "Operation timed out in $TimeoutSec s"
  }
  Receive-Job $job -ErrorAction Stop
}
